interface=wlan0
driver=nl80211

ssid=wifi_seguro_scrc
hw_mode=g
channel=1
wmm_enabled=1



wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=CCMP
auth_algs=1



auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=teste123



ieee8021x=1
eapol_key_index_workaround=1
